export const autoCompleteData = [
    "Product Information",
    "Order and Shipping",
    "Returns and Refunds",
    "Account Management",
    "Technical Support",
    "Billing and Payments",
    "Privacy and Security",
    "Usage and Tutorials",
    "Feedback and Suggestions",
    "Corporate or Business Inquiries",
    "Shipping to Different Locations",
    "Warranty and Repairs",
    "Account Deletion and Data Removal",
    "Subscription and Membership",
    "Legal and Terms of Service", 
  ];